services:
  - type: web
    name: app
    runtime: python
    buildCommand: |
      chmod +x ./drivers/chromedriver
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
